# Generated by Django 6.1 on 2026-08-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_group', models.CharField(choices=[('TITHE', 'Group TITHE'), ('COMBINED_OFFERING', 'Group COMBINED_OFFERING'), ('LCB_OFFERING', 'Group LCB_OFFERING'), ('LOOSE_OFFERING', 'Group LOOSE_OFFERING')], max_length=20)),
                ('subgroup', models.CharField(choices=[('local', 'local'), ('overall', 'overall'), ('ckc', 'ckc')], max_length=10)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('income_group', 'subgroup'), name='unique_group_subgroup_rule')],
            },
        ),
    ]
