# Generated by Django 6.1 on 2026-08-13 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_splitrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_group', models.CharField(choices=[('TITHE', 'Group TITHE'), ('COMBINED_OFFERING', 'Group COMBINED_OFFERING'), ('LCB_OFFERING', 'Group LCB_OFFERING'), ('LOOSE_OFFERING', 'Group LOOSE_OFFERING')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='mainapp.campus')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subgroup', models.CharField(choices=[('local', 'local'), ('overall', 'overall'), ('ckc', 'ckc')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='mainapp.income')),
            ],
        ),
    ]
